{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherium.fullname" . }}-api-gateway
  labels:
    {{- include "aetherium.apiGateway.labels" . | nindent 4 }}
  {{- with .Values.apiGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aetherium.apiGateway.selectorLabels" . | nindent 4 }}
{{- end }}
